version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono_app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: sample
      DB_PASSWORD: password
      DB_NAME: sample
    ports:
      - "3001:3000"

volumes:
  mysql_data:
